; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; ESP32-S3-ZERO board documentation can be found below.
; https://www.espboards.dev/esp32/esp32-s3-zero/


[env:ESP32-S3-ZERO]
platform = espressif32
framework = arduino
monitor_speed = 115200

board = esp32-s3-devkitm-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.partitions=default.csv
board_build.arduino.memory_type = qio_qspi
board_build.psram_type = qio
board_build.flash_mode = qio
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304

build_flags =
    -DBOARD_HAS_PSRAM=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_BT_NIMBLE_ENABLED=1
    -DCONFIG_NIMBLE_CPP_LOG_LEVEL=4
    -Iinclude

lib_deps =
    adafruit/Adafruit MPU6050@^2.2.9
    h2zero/NimBLE-Arduino@^2.3.7
    adafruit/Adafruit NeoPixel@^1.15.4

check_tool = cppcheck, clangtidy
check_severity = medium, high
check_skip_packages = yes
check_flags =
    cppcheck: --enable=all --suppress=missingInclude --suppress=unusedFunction --suppress=*:*.pio\*
    clangtidy: --checks=-llvm-header-guard --config-file=.clang-format
check_src_filters =
    +<src/>
    +<lib>
    +<include>